name: @name@
version: @version@
author: CubBossa
main: de.cubbossa.pathfinder.PathPlugin
# servers only run plugins with the same api-version or higher. Leave to 1.17
api-version: 1.17

depend:
  - ProtocolLib

softdepend:
  - PlaceholderAPI

permissions:
  pathfinder.command.pathfinder.info:
    default: op
  pathfinder.command.pathfinder.help:
    default: op
  pathfinder.command.pathfinder.reload:
    default: op
  pathfinder.command.pathfinder.import:
    default: op
  pathfinder.command.pathfinder.export:
    default: op
  pathfinder.command.find:
    default: true
  pathfinder.command.cancel_path:
    default: true
  pathfinder.command.roadmap.info:
    default: op
  pathfinder.command.roadmap.create:
    default: op
  pathfinder.command.roadmap.delete:
    default: op
  pathfinder.command.roadmap.editmode:
    default: op
  pathfinder.command.roadmap.list:
    default: op
  pathfinder.command.roadmap.forcefind:
    default: op
  pathfinder.command.roadmap.forceforget:
    default: op
  pathfinder.command.roadmap.set_visualizer:
    default: op
  pathfinder.command.roadmap.set_name:
    default: op
  pathfinder.command.roadmap.set_curvelength:
    default: op
  pathfinder.command.nodegroup.list:
    default: op
  pathfinder.command.nodegroup.create:
    default: op
  pathfinder.command.nodegroup.delete:
    default: op
  pathfinder.command.nodegroup.set_name:
    default: op
  pathfinder.command.nodegroup.set_findable:
    default: op
  pathfinder.command.nodegroup.searchterms.list:
    default: op
  pathfinder.command.nodegroup.searchterms.add:
    default: op
  pathfinder.command.nodegroup.searchterms.remove:
    default: op
  pathfinder.command.waypoint.info:
    default: op
  pathfinder.command.waypoint.list:
    default: op
  pathfinder.command.waypoint.create:
    default: op
  pathfinder.command.waypoint.delete:
    default: op
  pathfinder.command.waypoint.tp:
    default: op
  pathfinder.command.waypoint.tphere:
    default: op
  pathfinder.command.waypoint.connect:
    default: op
  pathfinder.command.waypoint.disconnect:
    default: op
  pathfinder.command.waypoint.set_curve_length:
    default: op
  pathfinder.command.waypoint.add_group:
    default: op
  pathfinder.command.waypoint.remove_group:
    default: op
  pathfinder.command.waypoint.clear_groups:
    default: op
  pathfinder.command.visualizer.list:
    default: op
  pathfinder.command.visualizer.create:
    default: op
  pathfinder.command.visualizer.delete:
    default: op
  pathfinder.command.visualizer.info:
    default: op
  pathfinder.command.visualizer.set_name:
    default: op
  pathfinder.command.visualizer.set_permission:
    default: op
  pathfinder.command.visualizer.set_interval:
    default: op
  pathfinder.command.visualizer.edit:
    default: op

  pathfinder.admin:
    default: op
    children:
      pathfinder.command.pathfinder.*: true
      pathfinder.command.roadmap.*: true
      pathfinder.command.nodegroup.*: true
      pathfinder.command.waypoint.*: true
      pathfinder.command.visualizer.*: true


