/*
 * This file is generated by jOOQ.
 */
package de.cubbossa.pathfinder.v3;


import de.cubbossa.pathfinder.v3.tables.*;
import de.cubbossa.pathfinder.v3.tables.records.*;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PathfinderDiscoveringsRecord> PATHFINDER_DISCOVERINGS__PK_PATHFINDER_DISCOVERINGS = Internal.createUniqueKey(PathfinderDiscoverings.PATHFINDER_DISCOVERINGS, DSL.name("pk_pathfinder_discoverings"), new TableField[]{PathfinderDiscoverings.PATHFINDER_DISCOVERINGS.DISCOVER_KEY, PathfinderDiscoverings.PATHFINDER_DISCOVERINGS.PLAYER_ID}, true);
    public static final UniqueKey<PathfinderEdgesRecord> PATHFINDER_EDGES__PK_PATHFINDER_EDGES = Internal.createUniqueKey(PathfinderEdges.PATHFINDER_EDGES, DSL.name("pk_pathfinder_edges"), new TableField[]{PathfinderEdges.PATHFINDER_EDGES.START_ID, PathfinderEdges.PATHFINDER_EDGES.END_ID}, true);
    public static final UniqueKey<PathfinderNodegroupsRecord> PATHFINDER_NODEGROUPS__PK_PATHFINDER_NODEGROUPS = Internal.createUniqueKey(PathfinderNodegroups.PATHFINDER_NODEGROUPS, DSL.name("pk_pathfinder_nodegroups"), new TableField[]{PathfinderNodegroups.PATHFINDER_NODEGROUPS.KEY}, true);
    public static final UniqueKey<PathfinderNodegroupsNodesRecord> PATHFINDER_NODEGROUPS_NODES__PK_PATHFINDER_NODEGROUPS_NODES = Internal.createUniqueKey(PathfinderNodegroupsNodes.PATHFINDER_NODEGROUPS_NODES, DSL.name("pk_pathfinder_nodegroups_nodes"), new TableField[]{PathfinderNodegroupsNodes.PATHFINDER_NODEGROUPS_NODES.GROUP_KEY, PathfinderNodegroupsNodes.PATHFINDER_NODEGROUPS_NODES.NODE_ID}, true);
    public static final UniqueKey<PathfinderNodesRecord> PATHFINDER_NODES__PK_PATHFINDER_NODES = Internal.createUniqueKey(PathfinderNodes.PATHFINDER_NODES, DSL.name("pk_pathfinder_nodes"), new TableField[]{PathfinderNodes.PATHFINDER_NODES.ID}, true);
    public static final UniqueKey<PathfinderPathVisualizerRecord> PATHFINDER_PATH_VISUALIZER__PK_PATHFINDER_PATH_VISUALIZER = Internal.createUniqueKey(PathfinderPathVisualizer.PATHFINDER_PATH_VISUALIZER, DSL.name("pk_pathfinder_path_visualizer"), new TableField[]{PathfinderPathVisualizer.PATHFINDER_PATH_VISUALIZER.KEY}, true);
    public static final UniqueKey<PathfinderRoadmapsRecord> PATHFINDER_ROADMAPS__PK_PATHFINDER_ROADMAPS = Internal.createUniqueKey(PathfinderRoadmaps.PATHFINDER_ROADMAPS, DSL.name("pk_pathfinder_roadmaps"), new TableField[]{PathfinderRoadmaps.PATHFINDER_ROADMAPS.KEY}, true);
    public static final UniqueKey<PathfinderSearchTermsRecord> PATHFINDER_SEARCH_TERMS__PK_PATHFINDER_SEARCH_TERMS = Internal.createUniqueKey(PathfinderSearchTerms.PATHFINDER_SEARCH_TERMS, DSL.name("pk_pathfinder_search_terms"), new TableField[]{PathfinderSearchTerms.PATHFINDER_SEARCH_TERMS.GROUP_KEY, PathfinderSearchTerms.PATHFINDER_SEARCH_TERMS.SEARCH_TERM}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<PathfinderNodegroupsNodesRecord, PathfinderNodegroupsRecord> PATHFINDER_NODEGROUPS_NODES__FK_PATHFINDER_NODEGROUPS_NODES_PK_PATHFINDER_NODEGROUPS = Internal.createForeignKey(PathfinderNodegroupsNodes.PATHFINDER_NODEGROUPS_NODES, DSL.name("fk_pathfinder_nodegroups_nodes_pk_pathfinder_nodegroups"), new TableField[]{PathfinderNodegroupsNodes.PATHFINDER_NODEGROUPS_NODES.GROUP_KEY}, Keys.PATHFINDER_NODEGROUPS__PK_PATHFINDER_NODEGROUPS, new TableField[]{PathfinderNodegroups.PATHFINDER_NODEGROUPS.KEY}, true);
    public static final ForeignKey<PathfinderNodegroupsNodesRecord, PathfinderNodesRecord> PATHFINDER_NODEGROUPS_NODES__FK_PATHFINDER_NODEGROUPS_NODES_PK_PATHFINDER_NODES = Internal.createForeignKey(PathfinderNodegroupsNodes.PATHFINDER_NODEGROUPS_NODES, DSL.name("fk_pathfinder_nodegroups_nodes_pk_pathfinder_nodes"), new TableField[]{PathfinderNodegroupsNodes.PATHFINDER_NODEGROUPS_NODES.NODE_ID}, Keys.PATHFINDER_NODES__PK_PATHFINDER_NODES, new TableField[]{PathfinderNodes.PATHFINDER_NODES.ID}, true);
    public static final ForeignKey<PathfinderNodesRecord, PathfinderRoadmapsRecord> PATHFINDER_NODES__FK_PATHFINDER_NODES_PK_PATHFINDER_ROADMAPS = Internal.createForeignKey(PathfinderNodes.PATHFINDER_NODES, DSL.name("fk_pathfinder_nodes_pk_pathfinder_roadmaps"), new TableField[]{PathfinderNodes.PATHFINDER_NODES.ROADMAP_KEY}, Keys.PATHFINDER_ROADMAPS__PK_PATHFINDER_ROADMAPS, new TableField[]{PathfinderRoadmaps.PATHFINDER_ROADMAPS.KEY}, true);
    public static final ForeignKey<PathfinderSearchTermsRecord, PathfinderNodegroupsRecord> PATHFINDER_SEARCH_TERMS__FK_PATHFINDER_SEARCH_TERMS_PK_PATHFINDER_NODEGROUPS = Internal.createForeignKey(PathfinderSearchTerms.PATHFINDER_SEARCH_TERMS, DSL.name("fk_pathfinder_search_terms_pk_pathfinder_nodegroups"), new TableField[]{PathfinderSearchTerms.PATHFINDER_SEARCH_TERMS.GROUP_KEY}, Keys.PATHFINDER_NODEGROUPS__PK_PATHFINDER_NODEGROUPS, new TableField[]{PathfinderNodegroups.PATHFINDER_NODEGROUPS.KEY}, true);
}
